CM-139: fix issues from QA
openimis/openimis-fe-tasks_management_js pull request #4
Opened 2023-07-10 13:38 UTC by jdolkowski

https://openimis.atlassian.net/browse/CM-138

This PR fixes comparing editedGroupTask and fetched task.

2023-07-10 15:44 UTC, dborowiecki requested changes
i left some comments, also i think that logic for removing whitespaces in backend (https://github.com/openimis/openimis-be-tasks_management_py/pull/7) could be added in scope of this PR.

2023-07-10 15:44 UTC, dborowiecki commented on src/pages/TaskGroupPage.js
> +      if (typeof data === 'object' && data !== null) {
if type of data === 'object' second statement is always true

2023-07-10 15:44 UTC, dborowiecki commented on src/pages/TaskGroupPage.js
> +    return !_.isEqual(taskGroupValues, editedTaskGroupValues);
Do you use getNestedValues to compare object? If so Loadash `_.isEqual(...)` should be enough to perform object comparison. If that's not the case and objects are more complex you can try adding [deep-equal](https://www.npmjs.com/package/deep-equal) package to the module. If I understand logic of getNestedValues correctly it has some flaws. For instance if we have objects: `{ 'a': 1, 'b': 0}` and `{ 'z': 1, 'x': 0}` it would return a false positive as values in order are the same, but prototype is different.

2023-07-11 08:35 UTC, jdolkowski commented on src/pages/TaskGroupPage.js
> +      if (typeof data === 'object' && data !== null) {
resolved

2023-07-11 09:19 UTC, jdolkowski commented on src/pages/TaskGroupPage.js
> +    return !_.isEqual(taskGroupValues, editedTaskGroupValues);
i changed how taskGroup is formatted. now it works with loaddash

2023-07-11 09:58 UTC, dborowiecki approved these changes

2023-07-11 09:58 UTC, merged